// PIIP Arsenal Tools Database
const toolsData = [
    {
        id: "metasploit-framework",
        name: "Metasploit Framework",
        category: "exploitation",
        description: "منصة متكاملة لاستغلال الثغرات وتطوير Payloads",
        githubUrl: "https://github.com/rapid7/metasploit-framework",
        os: ["windows", "linux", "macos"],
        size: "45.2 MB",
        version: "6.3.0",
        lastUpdate: "2024-01-20",
        downloads: 125000,
        rating: 4.9,
        license: "BSD-3-Clause",
        extendedDescription: "Metasploit Framework هي منصة متكاملة للاختراق الأخلاقي تتيح للمحترفين اختبار نقاط الضعف في الأنظمة والشبكات. تتضمن أدوات متقدمة لتطوير Payloads واستغلال الثغرات المعروفة."
    },
    {
        id: "nmap",
        name: "Nmap",
        category: "recon",
        description: "أقوى أداة لفحص الشبكات والـ Ports",
        githubUrl: "https://github.com/nmap/nmap",
        os: ["windows", "linux", "macos"],
        size: "8.7 MB",
        version: "7.94",
        lastUpdate: "2024-01-18",
        downloads: 98000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "Nmap هي الأداة الأكثر شهرة وموثوقية لفحص الشبكات واكتشاف الخدمات المفتوحة. تدعم تقنيات متقدمة مثل OS Detection وService Detection."
    },
    {
        id: "wireshark",
        name: "Wireshark",
        category: "recon",
        description: "تحليل حزم الشبكة واكتشاف الأنشطة المشبوهة",
        githubUrl: "https://gitlab.com/wireshark/wireshark",
        os: ["windows", "linux", "macos"],
        size: "32.1 MB",
        version: "4.2.0",
        lastUpdate: "2024-01-15",
        downloads: 75000,
        rating: 4.7,
        license: "GPL-2.0",
        extendedDescription: "Wireshark هو محلل حزم الشبكة الأكثر تطوراً في العالم. يتيح للمحترفين فحص حركة المرور بالتفصيل واكتشاف الأنشطة المشبوهة."
    },
    {
        id: "aircrack-ng",
        name: "Aircrack-ng",
        category: "exploitation",
        description: "تحليل وكسر كلمات سر شبكات Wi-Fi",
        githubUrl: "https://github.com/aircrack-ng/aircrack-ng",
        os: ["linux", "macos"],
        size: "5.2 MB",
        version: "1.7",
        lastUpdate: "2024-01-12",
        downloads: 68000,
        rating: 4.6,
        license: "GPL-2.0",
        extendedDescription: "Aircrack-ng هي مجموعة شاملة من الأدوات لاختبار أمان شبكات Wi-Fi. تتضمن أدوات لالتقاط الحزم وكسر كلمات المرور."
    },
    {
        id: "sqlmap",
        name: "sqlmap",
        category: "exploitation",
        description: "أداة مؤتمتة لاكتشاف واستغلال ثغرات SQL Injection",
        githubUrl: "https://github.com/sqlmapproject/sqlmap",
        os: ["windows", "linux", "macos"],
        size: "12.8 MB",
        version: "1.7.0",
        lastUpdate: "2024-01-10",
        downloads: 89000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "sqlmap هي أداة مفتوحة المصدر لاكتشاف واستغلال ثغرات SQL injection تلقائياً. تدعم قواعد بيانات متعددة وتقنيات متقدمة."
    },
    {
        id: "recon-ng",
        name: "Recon-ng",
        category: "osint",
        description: "منصة OSINT لجمع وتحليل المعلومات عن الأهداف",
        githubUrl: "https://github.com/lanmaster53/recon-ng",
        os: ["linux", "macos"],
        size: "3.4 MB",
        version: "5.1.2",
        lastUpdate: "2024-01-08",
        downloads: 42000,
        rating: 4.5,
        license: "GPL-3.0",
        extendedDescription: "Recon-ng هي منصة متقدمة لجمع المعلومات الاستخباراتية المفتوحة المصدر. تتيح للمحترفين جمع وتحليل البيانات من مصادر متعددة."
    },
    {
        id: "theharvester",
        name: "TheHarvester",
        category: "osint",
        description: "يجمع الإيميلات والدومينات من الإنترنت باستخدام محركات بحث",
        githubUrl: "https://github.com/laramies/theHarvester",
        os: ["linux", "macos"],
        size: "2.1 MB",
        version: "4.2.0",
        lastUpdate: "2024-01-05",
        downloads: 38000,
        rating: 4.4,
        license: "GPL-2.0",
        extendedDescription: "TheHarvester هي أداة فعالة لجمع المعلومات من محركات البحث والمواقع العامة. تساعد في اكتشاف البنية التحتية للمؤسسات."
    },
    {
        id: "sherlock",
        name: "Sherlock",
        category: "osint",
        description: "يبحث عن اسم مستخدم في أكثر من 300 موقع",
        githubUrl: "https://github.com/sherlock-project/sherlock",
        os: ["windows", "linux", "macos"],
        size: "1.8 MB",
        version: "0.14.3",
        lastUpdate: "2024-01-03",
        downloads: 52000,
        rating: 4.7,
        license: "MIT",
        extendedDescription: "Sherlock هي أداة قوية للبحث عن أسماء المستخدمين عبر مئات المواقع والمنصات الاجتماعية. تساعد في تتبع البصمة الرقمية."
    },
    {
        id: "ghunt",
        name: "GHunt",
        category: "osint",
        description: "استخراج معلومات حساسة من بريد Gmail فقط باستخدام الإيميل",
        githubUrl: "https://github.com/mxrch/GHunt",
        os: ["windows", "linux", "macos"],
        size: "0.9 MB",
        version: "3.0.0",
        lastUpdate: "2024-01-01",
        downloads: 28000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "GHunt هي أداة متخصصة في استخراج المعلومات من حسابات Gmail. تتيح الوصول إلى معلومات حساسة من خلال تقنيات متقدمة."
    },
    {
        id: "photon",
        name: "Photon",
        category: "osint",
        description: "زاحف ويب ذكي لجمع كل ما يمكن من روابط وبيانات",
        githubUrl: "https://github.com/s0md3v/Photon",
        os: ["windows", "linux", "macos"],
        size: "1.2 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-28",
        downloads: 35000,
        rating: 4.5,
        license: "GPL-3.0",
        extendedDescription: "Photon هو زاحف ويب ذكي مصمم لجمع المعلومات من المواقع بطريقة منهجية. يدعم استخراج الروابط والبيانات الحساسة."
    },
    {
        id: "sublist3r",
        name: "Sublist3r",
        category: "recon",
        description: "يبحث ويجمع Subdomains من أكثر من مصدر",
        githubUrl: "https://github.com/aboul3la/Sublist3r",
        os: ["linux", "macos"],
        size: "0.7 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-25",
        downloads: 32000,
        rating: 4.3,
        license: "GPL-2.0",
        extendedDescription: "Sublist3r هي أداة فعالة لاكتشاف النطاقات الفرعية باستخدام محركات البحث وقواعد البيانات العامة."
    },
    {
        id: "xsstrike",
        name: "XSStrike",
        category: "exploitation",
        description: "أداة هجومية ذكية ضد XSS بـ Fuzzer متطور",
        githubUrl: "https://github.com/s0md3v/XSStrike",
        os: ["windows", "linux", "macos"],
        size: "2.3 MB",
        version: "3.1.5",
        lastUpdate: "2023-12-22",
        downloads: 45000,
        rating: 4.6,
        license: "GPL-3.0",
        extendedDescription: "XSStrike هي أداة متقدمة لاختبار ثغرات XSS. تستخدم تقنيات ذكية لتجاوز الحماية واكتشاف الثغرات المعقدة."
    },
    {
        id: "dirsearch",
        name: "Dirsearch",
        category: "recon",
        description: "أداة للبحث عن الأدلة والمجلدات المخفية على المواقع",
        githubUrl: "https://github.com/maurosoria/dirsearch",
        os: ["windows", "linux", "macos"],
        size: "1.5 MB",
        version: "0.4.2",
        lastUpdate: "2023-12-20",
        downloads: 41000,
        rating: 4.4,
        license: "GPL-3.0",
        extendedDescription: "Dirsearch هي أداة سريعة وفعالة للبحث عن المجلدات والملفات المخفية على خوادم الويب."
    },
    {
        id: "amass",
        name: "Amass",
        category: "recon",
        description: "أداة شاملة لمسح البنية التحتية لنطاق معين",
        githubUrl: "https://github.com/owasp-amass/amass",
        os: ["windows", "linux", "macos"],
        size: "4.8 MB",
        version: "4.2.0",
        lastUpdate: "2023-12-18",
        downloads: 38000,
        rating: 4.7,
        license: "Apache-2.0",
        extendedDescription: "Amass هي أداة شاملة لمسح البنية التحتية للمؤسسات. تجمع معلومات من مصادر متعددة بطريقة منهجية."
    },
    {
        id: "dnsenum",
        name: "Dnsenum",
        category: "recon",
        description: "جمع معلومات DNS شاملة عن هدف معين",
        githubUrl: "https://github.com/fwaeytens/dnsenum",
        os: ["linux", "macos"],
        size: "0.6 MB",
        version: "1.2.4",
        lastUpdate: "2023-12-15",
        downloads: 25000,
        rating: 4.2,
        license: "GPL-2.0",
        extendedDescription: "Dnsenum هي أداة تقليدية لكنها فعالة لجمع معلومات DNS الشاملة عن الأهداف."
    },
    {
        id: "fierce",
        name: "Fierce",
        category: "recon",
        description: "أداة تقليدية لكنها فعالة جدًا لفحص DNS",
        githubUrl: "https://github.com/mschwager/fierce",
        os: ["linux", "macos"],
        size: "0.4 MB",
        version: "2.0.0",
        lastUpdate: "2023-12-12",
        downloads: 22000,
        rating: 4.3,
        license: "GPL-3.0",
        extendedDescription: "Fierce هي أداة DNS reconnaissance فعالة تساعد في اكتشاف النطاقات الفرعية والبنية التحتية."
    },
    {
        id: "dracnmap",
        name: "Dracnmap",
        category: "recon",
        description: "واجهة رسومية فوق Nmap تسهّل تنفيذ المسح",
        githubUrl: "https://github.com/Screetsec/Dracnmap",
        os: ["linux"],
        size: "3.2 MB",
        version: "2.0",
        lastUpdate: "2023-12-10",
        downloads: 18000,
        rating: 4.1,
        license: "MIT",
        extendedDescription: "Dracnmap يوفر واجهة رسومية سهلة الاستخدام فوق Nmap لتسهيل عمليات المسح للمبتدئين."
    },
    {
        id: "red-hawk",
        name: "Red Hawk",
        category: "recon",
        description: "أداة PHP شاملة لفحص المواقع والثغرات",
        githubUrl: "https://github.com/Tuhinshubhra/RED_HAWK",
        os: ["linux"],
        size: "2.8 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-08",
        downloads: 35000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "Red Hawk هي أداة PHP شاملة لفحص المواقع واكتشاف الثغرات الشائعة بطريقة مؤتمتة."
    },
    {
        id: "set",
        name: "SET (Social-Engineer Toolkit)",
        category: "exploitation",
        description: "إطار لهجمات الهندسة الاجتماعية والتصيّد",
        githubUrl: "https://github.com/trustedsec/social-engineer-toolkit",
        os: ["linux"],
        size: "15.6 MB",
        version: "8.0.0",
        lastUpdate: "2023-12-05",
        downloads: 42000,
        rating: 4.5,
        license: "BSD-3-Clause",
        extendedDescription: "SET هي منصة متقدمة لاختبار الهندسة الاجتماعية. تتضمن أدوات لإنشاء حملات التصيد المتطورة."
    },
    {
        id: "maltego",
        name: "Maltego CE",
        category: "osint",
        description: "أداة رسم بياني للمعلومات والعلاقات (واجهة رسومية)",
        githubUrl: "https://www.paterva.com/downloads.php",
        os: ["windows", "linux", "macos"],
        size: "45.0 MB",
        version: "4.3.0",
        lastUpdate: "2023-12-03",
        downloads: 28000,
        rating: 4.6,
        license: "Proprietary",
        extendedDescription: "Maltego هي أداة رسومية متقدمة لتحليل العلاقات والروابط بين البيانات. تستخدم في التحقيقات الجنائية الرقمية."
    },
    {
        id: "hydra",
        name: "Hydra",
        category: "exploitation",
        description: "تخمين كلمات السر للبروتوكولات المختلفة SSH, FTP, HTTP...",
        githubUrl: "https://github.com/vanhauser-thc/thc-hydra",
        os: ["windows", "linux", "macos"],
        size: "1.8 MB",
        version: "9.5",
        lastUpdate: "2023-11-30",
        downloads: 55000,
        rating: 4.7,
        license: "AGPL-3.0",
        extendedDescription: "Hydra هي أداة قوية لتخمين كلمات المرور عبر بروتوكولات متعددة. تدعم قواميس مخصصة وتقنيات متقدمة."
    },
    {
        id: "john-ripper",
        name: "John the Ripper",
        category: "exploitation",
        description: "كسر كلمات المرور المشفّرة بأسلوب سريع",
        githubUrl: "https://github.com/openwall/john",
        os: ["windows", "linux", "macos"],
        size: "3.2 MB",
        version: "1.9.0",
        lastUpdate: "2023-11-28",
        downloads: 48000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "John the Ripper هي أداة سريعة وفعالة لكسر كلمات المرور. تدعم خوارزميات تشفير متعددة."
    },
    {
        id: "hashcat",
        name: "Hashcat",
        category: "exploitation",
        description: "كسر كلمات السر باستخدام GPU بشكل رهيب السرعة",
        githubUrl: "https://github.com/hashcat/hashcat",
        os: ["windows", "linux", "macos"],
        size: "5.4 MB",
        version: "6.2.6",
        lastUpdate: "2023-11-25",
        downloads: 62000,
        rating: 4.9,
        license: "MIT",
        extendedDescription: "Hashcat هي أداة متقدمة لكسر كلمات المرور باستخدام قوة GPU. تعتبر الأسرع في العالم لهذا النوع من العمليات."
    },
    {
        id: "beef",
        name: "BeEF",
        category: "exploitation",
        description: "استغلال المتصفحات واستخدامها كـ zombies",
        githubUrl: "https://github.com/beefproject/beef",
        os: ["linux", "macos"],
        size: "8.9 MB",
        version: "0.5.0.0",
        lastUpdate: "2023-11-22",
        downloads: 38000,
        rating: 4.5,
        license: "GPL-2.0",
        extendedDescription: "BeEF هي منصة متقدمة لاستغلال المتصفحات وتحويلها إلى zombies تحت السيطرة."
    },
    {
        id: "empire",
        name: "Empire",
        category: "exploitation",
        description: "منصة Powershell & Python لاختراق Windows وPost-Exploitation",
        githubUrl: "https://github.com/BC-SECURITY/Empire",
        os: ["linux", "macos"],
        size: "12.3 MB",
        version: "5.9.0",
        lastUpdate: "2023-11-20",
        downloads: 45000,
        rating: 4.6,
        license: "BSD-3-Clause",
        extendedDescription: "Empire هي منصة متقدمة للاختراق تستخدم PowerShell وPython. متخصصة في اختراق أنظمة Windows."
    },
    {
        id: "pupy",
        name: "Pupy",
        category: "stealth",
        description: "RAT متطور عبر Python بخصائص Stealth",
        githubUrl: "https://github.com/n1nj4sec/pupy",
        os: ["linux", "macos"],
        size: "6.7 MB",
        version: "1.0.0",
        lastUpdate: "2023-11-18",
        downloads: 32000,
        rating: 4.4,
        license: "GPL-3.0",
        extendedDescription: "Pupy هو RAT متطور مكتوب بلغة Python. يتميز بقدرات stealth متقدمة وتقنيات evasions."
    },
    {
        id: "netcat",
        name: "Netcat",
        category: "stealth",
        description: "أداة الشبكة الشاملة لنقل البيانات وتشغيل الأوامر",
        githubUrl: "https://github.com/diegocr/netcat",
        os: ["windows", "linux", "macos"],
        size: "0.8 MB",
        version: "1.10",
        lastUpdate: "2023-11-15",
        downloads: 75000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "Netcat هي أداة الشبكة الأساسية التي تتيح نقل البيانات وتشغيل الأوامر عن بعد. تعتبر السويسري الجيش للشبكات."
    },
    {
        id: "nikto",
        name: "Nikto",
        category: "recon",
        description: "فاحص مواقع ويب لاكتشاف ثغرات خطيرة",
        githubUrl: "https://github.com/sullo/nikto",
        os: ["windows", "linux", "macos"],
        size: "2.1 MB",
        version: "2.1.6",
        lastUpdate: "2023-11-12",
        downloads: 41000,
        rating: 4.5,
        license: "GPL-2.0",
        extendedDescription: "Nikto هو فاحص ثغرات ويب شامل يكتشف الثغرات المعروفة في خوادم الويب والتطبيقات."
    },
    {
        id: "owasp-zap",
        name: "OWASP ZAP",
        category: "recon",
        description: "واجهة رسومية لفحص تطبيقات الويب مثل Burp",
        githubUrl: "https://github.com/zaproxy/zaproxy",
        os: ["windows", "linux", "macos"],
        size: "25.8 MB",
        version: "2.14.0",
        lastUpdate: "2023-11-10",
        downloads: 58000,
        rating: 4.7,
        license: "Apache-2.0",
        extendedDescription: "OWASP ZAP هي أداة مجانية ومفتوحة المصدر لفحص تطبيقات الويب. تعتبر بديلاً قوياً لـ Burp Suite."
    },
    {
        id: "burp-suite",
        name: "Burp Suite CE",
        category: "recon",
        description: "وكيل اعتراض وفحص لكل تفاصيل تطبيق الويب",
        githubUrl: "https://portswigger.net/burp",
        os: ["windows", "linux", "macos"],
        size: "35.2 MB",
        version: "2023.12.0",
        lastUpdate: "2023-11-08",
        downloads: 85000,
        rating: 4.9,
        license: "Proprietary",
        extendedDescription: "Burp Suite هي الأداة الأكثر شهرة في اختبار تطبيقات الويب. تتضمن أدوات متقدمة للاعتراض والفحص."
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = toolsData;
} 