// PIIP Arsenal Tools Database
const toolsData = [
    {
        id: "metasploit-framework",
        name: "Metasploit Framework",
        category: "exploitation",
        description: "منصة متكاملة لاستغلال الثغرات وتطوير Payloads",
        githubUrl: "https://github.com/rapid7/metasploit-framework",
        os: ["windows", "linux", "macos"],
        size: "45.2 MB",
        version: "6.3.0",
        lastUpdate: "2024-01-20",
        downloads: 125000,
        rating: 4.9,
        license: "BSD-3-Clause",
        extendedDescription: "Metasploit Framework هي منصة متكاملة للاختراق الأخلاقي تتيح للمحترفين اختبار نقاط الضعف في الأنظمة والشبكات. تتضمن أدوات متقدمة لتطوير Payloads واستغلال الثغرات المعروفة."
    },
    {
        id: "nmap",
        name: "Nmap",
        category: "recon",
        description: "أقوى أداة لفحص الشبكات والـ Ports",
        githubUrl: "https://github.com/nmap/nmap",
        os: ["windows", "linux", "macos"],
        size: "8.7 MB",
        version: "7.94",
        lastUpdate: "2024-01-18",
        downloads: 98000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "Nmap هي الأداة الأكثر شهرة وموثوقية لفحص الشبكات واكتشاف الخدمات المفتوحة. تدعم تقنيات متقدمة مثل OS Detection وService Detection."
    },
    {
        id: "wireshark",
        name: "Wireshark",
        category: "recon",
        description: "تحليل حزم الشبكة واكتشاف الأنشطة المشبوهة",
        githubUrl: "https://gitlab.com/wireshark/wireshark",
        os: ["windows", "linux", "macos"],
        size: "32.1 MB",
        version: "4.2.0",
        lastUpdate: "2024-01-15",
        downloads: 75000,
        rating: 4.7,
        license: "GPL-2.0",
        extendedDescription: "Wireshark هو محلل حزم الشبكة الأكثر تطوراً في العالم. يتيح للمحترفين فحص حركة المرور بالتفصيل واكتشاف الأنشطة المشبوهة."
    },
    {
        id: "aircrack-ng",
        name: "Aircrack-ng",
        category: "exploitation",
        description: "تحليل وكسر كلمات سر شبكات Wi-Fi",
        githubUrl: "https://github.com/aircrack-ng/aircrack-ng",
        os: ["linux", "macos"],
        size: "5.2 MB",
        version: "1.7",
        lastUpdate: "2024-01-12",
        downloads: 68000,
        rating: 4.6,
        license: "GPL-2.0",
        extendedDescription: "Aircrack-ng هي مجموعة شاملة من الأدوات لاختبار أمان شبكات Wi-Fi. تتضمن أدوات لالتقاط الحزم وكسر كلمات المرور."
    },
    {
        id: "sqlmap",
        name: "sqlmap",
        category: "exploitation",
        description: "أداة مؤتمتة لاكتشاف واستغلال ثغرات SQL Injection",
        githubUrl: "https://github.com/sqlmapproject/sqlmap",
        os: ["windows", "linux", "macos"],
        size: "12.8 MB",
        version: "1.7.0",
        lastUpdate: "2024-01-10",
        downloads: 89000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "sqlmap هي أداة مفتوحة المصدر لاكتشاف واستغلال ثغرات SQL injection تلقائياً. تدعم قواعد بيانات متعددة وتقنيات متقدمة."
    },
    {
        id: "recon-ng",
        name: "Recon-ng",
        category: "osint",
        description: "منصة OSINT لجمع وتحليل المعلومات عن الأهداف",
        githubUrl: "https://github.com/lanmaster53/recon-ng",
        os: ["linux", "macos"],
        size: "3.4 MB",
        version: "5.1.2",
        lastUpdate: "2024-01-08",
        downloads: 42000,
        rating: 4.5,
        license: "GPL-3.0",
        extendedDescription: "Recon-ng هي منصة متقدمة لجمع المعلومات الاستخباراتية المفتوحة المصدر. تتيح للمحترفين جمع وتحليل البيانات من مصادر متعددة."
    },
    {
        id: "theharvester",
        name: "TheHarvester",
        category: "osint",
        description: "يجمع الإيميلات والدومينات من الإنترنت باستخدام محركات بحث",
        githubUrl: "https://github.com/laramies/theHarvester",
        os: ["linux", "macos"],
        size: "2.1 MB",
        version: "4.2.0",
        lastUpdate: "2024-01-05",
        downloads: 38000,
        rating: 4.4,
        license: "GPL-2.0",
        extendedDescription: "TheHarvester هي أداة فعالة لجمع المعلومات من محركات البحث والمواقع العامة. تساعد في اكتشاف البنية التحتية للمؤسسات."
    },
    {
        id: "sherlock",
        name: "Sherlock",
        category: "osint",
        description: "يبحث عن اسم مستخدم في أكثر من 300 موقع",
        githubUrl: "https://github.com/sherlock-project/sherlock",
        os: ["windows", "linux", "macos"],
        size: "1.8 MB",
        version: "0.14.3",
        lastUpdate: "2024-01-03",
        downloads: 52000,
        rating: 4.7,
        license: "MIT",
        extendedDescription: "Sherlock هي أداة قوية للبحث عن أسماء المستخدمين عبر مئات المواقع والمنصات الاجتماعية. تساعد في تتبع البصمة الرقمية."
    },
    {
        id: "ghunt",
        name: "GHunt",
        category: "osint",
        description: "استخراج معلومات حساسة من بريد Gmail فقط باستخدام الإيميل",
        githubUrl: "https://github.com/mxrch/GHunt",
        os: ["windows", "linux", "macos"],
        size: "0.9 MB",
        version: "3.0.0",
        lastUpdate: "2024-01-01",
        downloads: 28000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "GHunt هي أداة متخصصة في استخراج المعلومات من حسابات Gmail. تتيح الوصول إلى معلومات حساسة من خلال تقنيات متقدمة."
    },
    {
        id: "photon",
        name: "Photon",
        category: "osint",
        description: "زاحف ويب ذكي لجمع كل ما يمكن من روابط وبيانات",
        githubUrl: "https://github.com/s0md3v/Photon",
        os: ["windows", "linux", "macos"],
        size: "1.2 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-28",
        downloads: 35000,
        rating: 4.5,
        license: "GPL-3.0",
        extendedDescription: "Photon هو زاحف ويب ذكي مصمم لجمع المعلومات من المواقع بطريقة منهجية. يدعم استخراج الروابط والبيانات الحساسة."
    },
    {
        id: "sublist3r",
        name: "Sublist3r",
        category: "recon",
        description: "يبحث ويجمع Subdomains من أكثر من مصدر",
        githubUrl: "https://github.com/aboul3la/Sublist3r",
        os: ["linux", "macos"],
        size: "0.7 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-25",
        downloads: 32000,
        rating: 4.3,
        license: "GPL-2.0",
        extendedDescription: "Sublist3r هي أداة فعالة لاكتشاف النطاقات الفرعية باستخدام محركات البحث وقواعد البيانات العامة."
    },
    {
        id: "xsstrike",
        name: "XSStrike",
        category: "exploitation",
        description: "أداة هجومية ذكية ضد XSS بـ Fuzzer متطور",
        githubUrl: "https://github.com/s0md3v/XSStrike",
        os: ["windows", "linux", "macos"],
        size: "2.3 MB",
        version: "3.1.5",
        lastUpdate: "2023-12-22",
        downloads: 45000,
        rating: 4.6,
        license: "GPL-3.0",
        extendedDescription: "XSStrike هي أداة متقدمة لاختبار ثغرات XSS. تستخدم تقنيات ذكية لتجاوز الحماية واكتشاف الثغرات المعقدة."
    },
    {
        id: "dirsearch",
        name: "Dirsearch",
        category: "recon",
        description: "أداة للبحث عن الأدلة والمجلدات المخفية على المواقع",
        githubUrl: "https://github.com/maurosoria/dirsearch",
        os: ["windows", "linux", "macos"],
        size: "1.5 MB",
        version: "0.4.2",
        lastUpdate: "2023-12-20",
        downloads: 41000,
        rating: 4.4,
        license: "GPL-3.0",
        extendedDescription: "Dirsearch هي أداة سريعة وفعالة للبحث عن المجلدات والملفات المخفية على خوادم الويب."
    },
    {
        id: "amass",
        name: "Amass",
        category: "recon",
        description: "أداة شاملة لمسح البنية التحتية لنطاق معين",
        githubUrl: "https://github.com/owasp-amass/amass",
        os: ["windows", "linux", "macos"],
        size: "4.8 MB",
        version: "4.2.0",
        lastUpdate: "2023-12-18",
        downloads: 38000,
        rating: 4.7,
        license: "Apache-2.0",
        extendedDescription: "Amass هي أداة شاملة لمسح البنية التحتية للمؤسسات. تجمع معلومات من مصادر متعددة بطريقة منهجية."
    },
    {
        id: "dnsenum",
        name: "Dnsenum",
        category: "recon",
        description: "جمع معلومات DNS شاملة عن هدف معين",
        githubUrl: "https://github.com/fwaeytens/dnsenum",
        os: ["linux", "macos"],
        size: "0.6 MB",
        version: "1.2.4",
        lastUpdate: "2023-12-15",
        downloads: 25000,
        rating: 4.2,
        license: "GPL-2.0",
        extendedDescription: "Dnsenum هي أداة تقليدية لكنها فعالة لجمع معلومات DNS الشاملة عن الأهداف."
    },
    {
        id: "fierce",
        name: "Fierce",
        category: "recon",
        description: "أداة تقليدية لكنها فعالة جدًا لفحص DNS",
        githubUrl: "https://github.com/mschwager/fierce",
        os: ["linux", "macos"],
        size: "0.4 MB",
        version: "2.0.0",
        lastUpdate: "2023-12-12",
        downloads: 22000,
        rating: 4.3,
        license: "GPL-3.0",
        extendedDescription: "Fierce هي أداة DNS reconnaissance فعالة تساعد في اكتشاف النطاقات الفرعية والبنية التحتية."
    },
    {
        id: "dracnmap",
        name: "Dracnmap",
        category: "recon",
        description: "واجهة رسومية فوق Nmap تسهّل تنفيذ المسح",
        githubUrl: "https://github.com/Screetsec/Dracnmap",
        os: ["linux"],
        size: "3.2 MB",
        version: "2.0",
        lastUpdate: "2023-12-10",
        downloads: 18000,
        rating: 4.1,
        license: "MIT",
        extendedDescription: "Dracnmap يوفر واجهة رسومية سهلة الاستخدام فوق Nmap لتسهيل عمليات المسح للمبتدئين."
    },
    {
        id: "red-hawk",
        name: "Red Hawk",
        category: "recon",
        description: "أداة PHP شاملة لفحص المواقع والثغرات",
        githubUrl: "https://github.com/Tuhinshubhra/RED_HAWK",
        os: ["linux"],
        size: "2.8 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-08",
        downloads: 35000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "Red Hawk هي أداة PHP شاملة لفحص المواقع واكتشاف الثغرات الشائعة بطريقة مؤتمتة."
    },
    {
        id: "set",
        name: "SET (Social-Engineer Toolkit)",
        category: "exploitation",
        description: "إطار لهجمات الهندسة الاجتماعية والتصيّد",
        githubUrl: "https://github.com/trustedsec/social-engineer-toolkit",
        os: ["linux"],
        size: "15.6 MB",
        version: "8.0.0",
        lastUpdate: "2023-12-05",
        downloads: 42000,
        rating: 4.5,
        license: "BSD-3-Clause",
        extendedDescription: "SET هي منصة متقدمة لاختبار الهندسة الاجتماعية. تتضمن أدوات لإنشاء حملات التصيد المتطورة."
    },
    {
        id: "maltego",
        name: "Maltego CE",
        category: "osint",
        description: "أداة رسم بياني للمعلومات والعلاقات (واجهة رسومية)",
        githubUrl: "https://www.paterva.com/downloads.php",
        os: ["windows", "linux", "macos"],
        size: "45.0 MB",
        version: "4.3.0",
        lastUpdate: "2023-12-03",
        downloads: 28000,
        rating: 4.6,
        license: "Proprietary",
        extendedDescription: "Maltego هي أداة رسومية متقدمة لتحليل العلاقات والروابط بين البيانات. تستخدم في التحقيقات الجنائية الرقمية."
    },
    {
        id: "hydra",
        name: "Hydra",
        category: "exploitation",
        description: "تخمين كلمات السر للبروتوكولات المختلفة SSH, FTP, HTTP...",
        githubUrl: "https://github.com/vanhauser-thc/thc-hydra",
        os: ["windows", "linux", "macos"],
        size: "1.8 MB",
        version: "9.5",
        lastUpdate: "2023-11-30",
        downloads: 55000,
        rating: 4.7,
        license: "AGPL-3.0",
        extendedDescription: "Hydra هي أداة قوية لتخمين كلمات المرور عبر بروتوكولات متعددة. تدعم قواميس مخصصة وتقنيات متقدمة."
    },
    {
        id: "john-ripper",
        name: "John the Ripper",
        category: "exploitation",
        description: "كسر كلمات المرور المشفّرة بأسلوب سريع",
        githubUrl: "https://github.com/openwall/john",
        os: ["windows", "linux", "macos"],
        size: "3.2 MB",
        version: "1.9.0",
        lastUpdate: "2023-11-28",
        downloads: 48000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "John the Ripper هي أداة سريعة وفعالة لكسر كلمات المرور. تدعم خوارزميات تشفير متعددة."
    },
    {
        id: "hashcat",
        name: "Hashcat",
        category: "exploitation",
        description: "كسر كلمات السر باستخدام GPU بشكل رهيب السرعة",
        githubUrl: "https://github.com/hashcat/hashcat",
        os: ["windows", "linux", "macos"],
        size: "5.4 MB",
        version: "6.2.6",
        lastUpdate: "2023-11-25",
        downloads: 62000,
        rating: 4.9,
        license: "MIT",
        extendedDescription: "Hashcat هي أداة متقدمة لكسر كلمات المرور باستخدام قوة GPU. تعتبر الأسرع في العالم لهذا النوع من العمليات."
    },
    {
        id: "beef",
        name: "BeEF",
        category: "exploitation",
        description: "استغلال المتصفحات واستخدامها كـ zombies",
        githubUrl: "https://github.com/beefproject/beef",
        os: ["linux", "macos"],
        size: "8.9 MB",
        version: "0.5.0.0",
        lastUpdate: "2023-11-22",
        downloads: 38000,
        rating: 4.5,
        license: "GPL-2.0",
        extendedDescription: "BeEF هي منصة متقدمة لاستغلال المتصفحات وتحويلها إلى zombies تحت السيطرة."
    },
    {
        id: "empire",
        name: "Empire",
        category: "exploitation",
        description: "منصة Powershell & Python لاختراق Windows وPost-Exploitation",
        githubUrl: "https://github.com/BC-SECURITY/Empire",
        os: ["linux", "macos"],
        size: "12.3 MB",
        version: "5.9.0",
        lastUpdate: "2023-11-20",
        downloads: 45000,
        rating: 4.6,
        license: "BSD-3-Clause",
        extendedDescription: "Empire هي منصة متقدمة للاختراق تستخدم PowerShell وPython. متخصصة في اختراق أنظمة Windows."
    },
    {
        id: "pupy",
        name: "Pupy",
        category: "stealth",
        description: "RAT متطور عبر Python بخصائص Stealth",
        githubUrl: "https://github.com/n1nj4sec/pupy",
        os: ["linux", "macos"],
        size: "6.7 MB",
        version: "1.0.0",
        lastUpdate: "2023-11-18",
        downloads: 32000,
        rating: 4.4,
        license: "GPL-3.0",
        extendedDescription: "Pupy هو RAT متطور مكتوب بلغة Python. يتميز بقدرات stealth متقدمة وتقنيات evasions."
    },
    {
        id: "netcat",
        name: "Netcat",
        category: "stealth",
        description: "أداة الشبكة الشاملة لنقل البيانات وتشغيل الأوامر",
        githubUrl: "https://github.com/diegocr/netcat",
        os: ["windows", "linux", "macos"],
        size: "0.8 MB",
        version: "1.10",
        lastUpdate: "2023-11-15",
        downloads: 75000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "Netcat هي أداة الشبكة الأساسية التي تتيح نقل البيانات وتشغيل الأوامر عن بعد. تعتبر السويسري الجيش للشبكات."
    },
    {
        id: "nikto",
        name: "Nikto",
        category: "recon",
        description: "فاحص مواقع ويب لاكتشاف ثغرات خطيرة",
        githubUrl: "https://github.com/sullo/nikto",
        os: ["windows", "linux", "macos"],
        size: "2.1 MB",
        version: "2.1.6",
        lastUpdate: "2023-11-12",
        downloads: 41000,
        rating: 4.5,
        license: "GPL-2.0",
        extendedDescription: "Nikto هو فاحص ثغرات ويب شامل يكتشف الثغرات المعروفة في خوادم الويب والتطبيقات."
    },
    {
        id: "owasp-zap",
        name: "OWASP ZAP",
        category: "recon",
        description: "واجهة رسومية لفحص تطبيقات الويب مثل Burp",
        githubUrl: "https://github.com/zaproxy/zaproxy",
        os: ["windows", "linux", "macos"],
        size: "25.8 MB",
        version: "2.14.0",
        lastUpdate: "2023-11-10",
        downloads: 58000,
        rating: 4.7,
        license: "Apache-2.0",
        extendedDescription: "OWASP ZAP هي أداة مجانية ومفتوحة المصدر لفحص تطبيقات الويب. تعتبر بديلاً قوياً لـ Burp Suite."
    },
    {
        id: "burp-suite",
        name: "Burp Suite CE",
        category: "recon",
        description: "وكيل اعتراض وفحص لكل تفاصيل تطبيق الويب",
        githubUrl: "https://portswigger.net/burp",
        os: ["windows", "linux", "macos"],
        size: "35.2 MB",
        version: "2023.12.0",
        lastUpdate: "2023-11-08",
        downloads: 85000,
        rating: 4.9,
        license: "Proprietary",
        extendedDescription: "Burp Suite هي الأداة الأكثر شهرة في اختبار تطبيقات الويب. تتضمن أدوات متقدمة للاعتراض والفحص."
    },
    {
        id: "cobalt-strike",
        name: "Cobalt Strike",
        category: "exploitation",
        description: "منصة متقدمة للاختراق والـ Post-Exploitation",
        githubUrl: "https://www.cobaltstrike.com/",
        os: ["windows", "linux", "macos"],
        size: "28.5 MB",
        version: "4.9.0",
        lastUpdate: "2024-01-25",
        downloads: 35000,
        rating: 4.9,
        license: "Proprietary",
        extendedDescription: "Cobalt Strike هي منصة متقدمة للاختراق تستخدم في اختبار الاختراق المحترف. تتضمن أدوات متطورة للـ Post-Exploitation."
    },
    {
        id: "bloodhound",
        name: "BloodHound",
        category: "recon",
        description: "تحليل علاقات Active Directory واكتشاف مسارات الهجوم",
        githubUrl: "https://github.com/BloodHoundAD/BloodHound",
        os: ["windows", "linux", "macos"],
        size: "15.2 MB",
        version: "4.3.0",
        lastUpdate: "2024-01-22",
        downloads: 42000,
        rating: 4.8,
        license: "GPL-3.0",
        extendedDescription: "BloodHound هي أداة متقدمة لتحليل علاقات Active Directory. تساعد في اكتشاف مسارات الهجوم المحتملة."
    },
    {
        id: "responder",
        name: "Responder",
        category: "exploitation",
        description: "أداة لاستغلال بروتوكولات الشبكة مثل LLMNR وNBT-NS",
        githubUrl: "https://github.com/lgandx/Responder",
        os: ["linux", "macos"],
        size: "2.8 MB",
        version: "3.1.3.0",
        lastUpdate: "2024-01-19",
        downloads: 38000,
        rating: 4.7,
        license: "GPL-3.0",
        extendedDescription: "Responder هي أداة فعالة لاستغلال بروتوكولات الشبكة الضعيفة. تستخدم في اختبارات اختراق الشبكات الداخلية."
    },
    {
        id: "mitmproxy",
        name: "mitmproxy",
        category: "recon",
        description: "وكيل اعتراض متقدم لفحص حركة مرور HTTPS",
        githubUrl: "https://github.com/mitmproxy/mitmproxy",
        os: ["windows", "linux", "macos"],
        size: "8.4 MB",
        version: "10.1.0",
        lastUpdate: "2024-01-17",
        downloads: 52000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "mitmproxy هو وكيل اعتراض متقدم يدعم فحص حركة مرور HTTPS. يوفر واجهة سطر أوامر وواجهة ويب."
    },
    {
        id: "gobuster",
        name: "Gobuster",
        category: "recon",
        description: "أداة سريعة للبحث عن المجلدات والملفات المخفية",
        githubUrl: "https://github.com/OJ/gobuster",
        os: ["windows", "linux", "macos"],
        size: "3.2 MB",
        version: "3.6.0",
        lastUpdate: "2024-01-15",
        downloads: 45000,
        rating: 4.5,
        license: "Apache-2.0",
        extendedDescription: "Gobuster هي أداة سريعة مكتوبة بلغة Go للبحث عن المجلدات والملفات المخفية. تتميز بالسرعة والفعالية."
    },
    {
        id: "ffuf",
        name: "ffuf",
        category: "recon",
        description: "أداة Fuzzing سريعة للويب مكتوبة بلغة Go",
        githubUrl: "https://github.com/ffuf/ffuf",
        os: ["windows", "linux", "macos"],
        size: "2.1 MB",
        version: "2.0.0",
        lastUpdate: "2024-01-13",
        downloads: 48000,
        rating: 4.7,
        license: "MIT",
        extendedDescription: "ffuf هي أداة fuzzing سريعة ومتعددة الاستخدامات للويب. مكتوبة بلغة Go وتتميز بالسرعة."
    },
    {
        id: "nuclei",
        name: "Nuclei",
        category: "recon",
        description: "محرك فحص سريع وقابل للتخصيص للثغرات المعروفة",
        githubUrl: "https://github.com/projectdiscovery/nuclei",
        os: ["windows", "linux", "macos"],
        size: "4.5 MB",
        version: "3.1.0",
        lastUpdate: "2024-01-11",
        downloads: 65000,
        rating: 4.8,
        license: "MIT",
        extendedDescription: "Nuclei هو محرك فحص سريع وقابل للتخصيص. يدعم قوالب مخصصة للكشف عن الثغرات المعروفة."
    },
    {
        id: "subfinder",
        name: "Subfinder",
        category: "recon",
        description: "أداة سريعة لاكتشاف النطاقات الفرعية من مصادر متعددة",
        githubUrl: "https://github.com/projectdiscovery/subfinder",
        os: ["windows", "linux", "macos"],
        size: "2.8 MB",
        version: "2.6.0",
        lastUpdate: "2024-01-09",
        downloads: 55000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "Subfinder هي أداة سريعة لاكتشاف النطاقات الفرعية. تجمع من مصادر متعددة بطريقة فعالة."
    },
    {
        id: "httpx",
        name: "httpx",
        category: "recon",
        description: "أداة سريعة لفحص HTTP probes مع دعم متقدم للـ HTTP",
        githubUrl: "https://github.com/projectdiscovery/httpx",
        os: ["windows", "linux", "macos"],
        size: "3.1 MB",
        version: "1.3.0",
        lastUpdate: "2024-01-07",
        downloads: 42000,
        rating: 4.5,
        license: "MIT",
        extendedDescription: "httpx هي أداة سريعة لفحص HTTP probes. تدعم تقنيات متقدمة مثل HTTP/2 وWebSocket."
    },
    {
        id: "naabu",
        name: "Naabu",
        category: "recon",
        description: "أداة سريعة لفحص المنافذ مكتوبة بلغة Go",
        githubUrl: "https://github.com/projectdiscovery/naabu",
        os: ["windows", "linux", "macos"],
        size: "1.9 MB",
        version: "2.1.0",
        lastUpdate: "2024-01-05",
        downloads: 38000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "Naabu هي أداة سريعة لفحص المنافذ مكتوبة بلغة Go. تتميز بالسرعة والفعالية في المسح."
    },
    {
        id: "shodan-cli",
        name: "Shodan CLI",
        category: "osint",
        description: "واجهة سطر أوامر لـ Shodan للبحث في الأجهزة المتصلة",
        githubUrl: "https://github.com/achillean/shodan-python",
        os: ["windows", "linux", "macos"],
        size: "0.8 MB",
        version: "1.30.0",
        lastUpdate: "2024-01-03",
        downloads: 28000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "Shodan CLI هي واجهة سطر أوامر لـ Shodan. تتيح البحث في قاعدة بيانات الأجهزة المتصلة بالإنترنت."
    },
    {
        id: "the-eye",
        name: "The Eye",
        category: "osint",
        description: "أداة لجمع المعلومات من مصادر متعددة بطريقة مؤتمتة",
        githubUrl: "https://github.com/Edu4rdSHL/the-eye",
        os: ["linux", "macos"],
        size: "1.2 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-01",
        downloads: 15000,
        rating: 4.3,
        license: "GPL-3.0",
        extendedDescription: "The Eye هي أداة لجمع المعلومات من مصادر متعددة. تساعد في جمع البيانات بطريقة منهجية."
    },
    {
        id: "holehe",
        name: "holehe",
        category: "osint",
        description: "أداة للتحقق من وجود إيميل في مواقع مختلفة",
        githubUrl: "https://github.com/megadose/holehe",
        os: ["windows", "linux", "macos"],
        size: "0.6 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-30",
        downloads: 22000,
        rating: 4.4,
        license: "GPL-3.0",
        extendedDescription: "holehe هي أداة للتحقق من وجود إيميل في مواقع مختلفة. تساعد في تتبع البصمة الرقمية."
    },
    {
        id: "breach-parse",
        name: "Breach-Parse",
        category: "osint",
        description: "أداة لتحليل قوائم كلمات المرور المسربة",
        githubUrl: "https://github.com/hmaverickadams/breach-parse",
        os: ["linux", "macos"],
        size: "5.2 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-28",
        downloads: 18000,
        rating: 4.2,
        license: "MIT",
        extendedDescription: "Breach-Parse هي أداة لتحليل قوائم كلمات المرور المسربة. تساعد في تحليل البيانات المسربة."
    },
    {
        id: "crunch",
        name: "Crunch",
        category: "exploitation",
        description: "مولد قواميس كلمات المرور القابلة للتخصيص",
        githubUrl: "https://github.com/crunchsec/crunch",
        os: ["windows", "linux", "macos"],
        size: "0.4 MB",
        version: "3.6",
        lastUpdate: "2023-12-26",
        downloads: 32000,
        rating: 4.5,
        license: "GPL-2.0",
        extendedDescription: "Crunch هو مولد قواميس كلمات المرور القابلة للتخصيص. يدعم أنماط متقدمة لتوليد كلمات المرور."
    },
    {
        id: "cewl",
        name: "CeWL",
        category: "exploitation",
        description: "أداة لاستخراج كلمات من مواقع الويب لإنشاء قواميس",
        githubUrl: "https://github.com/digininja/CeWL",
        os: ["linux", "macos"],
        size: "0.8 MB",
        version: "6.0.0",
        lastUpdate: "2023-12-24",
        downloads: 25000,
        rating: 4.3,
        license: "GPL-3.0",
        extendedDescription: "CeWL هي أداة لاستخراج كلمات من مواقع الويب. تساعد في إنشاء قواميس مخصصة للهجمات."
    },
    {
        id: "radare2-cutter",
        name: "Radare2 + Cutter/Iaito",
        category: "reverse",
        description: "إطار تحليل ثنائي مفتوح المصدر لتفكيك البرامج والهندسة العكسية",
        githubUrl: "https://github.com/radareorg/radare2",
        os: ["windows", "linux", "macos"],
        size: "12.5 MB",
        version: "5.8.0",
        lastUpdate: "2024-01-30",
        downloads: 45000,
        rating: 4.7,
        license: "LGPL-3.0",
        extendedDescription: "Radare2 هو إطار تحليل ثنائي مفتوح المصدر لتفكيك البرامج، التنقيح (debugging)، والهندسة العكسية. يستعمل في اختبارات الثغرات، CTF، وتحليل الملفات التنفيذية."
    },
    {
        id: "ghidra",
        name: "Ghidra",
        category: "reverse",
        description: "أداة تفكيك وتحليل ثنائيات من وكالة الأمن القومي الأمريكية",
        githubUrl: "https://github.com/NationalSecurityAgency/ghidra",
        os: ["windows", "linux", "macos"],
        size: "85.2 MB",
        version: "10.3.0",
        lastUpdate: "2024-01-28",
        downloads: 68000,
        rating: 4.8,
        license: "Apache-2.0",
        extendedDescription: "Ghidra هي أداة تفكيك وتحليل ثنائيات من تطوير وكالة الأمن القومي الأمريكية، تدعم العديد من المعماريات. تستخدم في تحليل البرمجيات الخبيثة والهندسة العكسية."
    },
    {
        id: "binary-ninja",
        name: "Binary Ninja",
        category: "reverse",
        description: "منصة تحليل ثنائية متقدمة تجارية مع واجهة رسومية",
        githubUrl: "https://binary.ninja",
        os: ["windows", "linux", "macos"],
        size: "45.8 MB",
        version: "4.0.0",
        lastUpdate: "2024-01-26",
        downloads: 25000,
        rating: 4.9,
        license: "Proprietary",
        extendedDescription: "Binary Ninja هي منصة تحليل ثنائية متقدمة تجارية مع واجهة رسومية ودعم لعدة لغات. تستخدم في تفكيك الكود وتحليل الثغرات بواجهة مرنة وديناميكية."
    },
    {
        id: "diffstega",
        name: "DiffStega",
        category: "stego",
        description: "نظام Steganography يعتمد على نماذج Diffusion لإخفاء المعلومات",
        githubUrl: "https://github.com/evtricks/DiffStega",
        os: ["linux", "macos"],
        size: "8.2 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-24",
        downloads: 12000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "DiffStega هو نظام Steganography يعتمد على نماذج Diffusion لإخفاء المعلومات داخل الصور دون تدريب مسبق. يستخدم في تهريب بيانات داخل الصور بأسلوب غير قابل للكشف بسهولة."
    },
    {
        id: "screedsolo",
        name: "SCReedSolo",
        category: "stego",
        description: "أداة تستخدم تقنية LSB مع تشفير Fernet وتصحيح الأخطاء",
        githubUrl: "https://github.com/abdeladim-s/SCReedSolo",
        os: ["windows", "linux", "macos"],
        size: "2.1 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-22",
        downloads: 8500,
        rating: 4.3,
        license: "MIT",
        extendedDescription: "SCReedSolo هي أداة تستخدم تقنية LSB مع تشفير Fernet وتصحيح الأخطاء بطريقة Reed-Solomon. تستخدم في إخفاء البيانات داخل الصور مع مقاومة التلف أو الفقد."
    },
    {
        id: "psydduck",
        name: "PSyDUCK",
        category: "stego",
        description: "تقنية إخفاء بيانات في latent space عبر Diffusion Models",
        githubUrl: "https://arxiv.org/abs/2401.12233",
        os: ["linux", "macos"],
        size: "15.6 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-20",
        downloads: 9800,
        rating: 4.5,
        license: "MIT",
        extendedDescription: "PSyDUCK هي تقنية إخفاء بيانات في latent space عبر Diffusion Models دون تدريب مسبق. تستخدم في Steganography عالية الفاعلية بصريًا وغير قابلة للرصد التقليدي."
    },
    {
        id: "aletheia",
        name: "Aletheia",
        category: "stego",
        description: "أداة تحليل بيانات مخفية في الصور باستخدام تعلم عميق",
        githubUrl: "https://github.com/daniellerch/aletheia",
        os: ["linux", "macos"],
        size: "6.8 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-18",
        downloads: 15000,
        rating: 4.6,
        license: "GPL-3.0",
        extendedDescription: "Aletheia هي أداة تحليل بيانات مخفية في الصور (Steganalysis) باستخدام خوارزميات تعلم عميق. تستخدم في كشف أساليب الإخفاء مثل F5، LSB، وغيرها."
    },
    {
        id: "steg-detector",
        name: "STEG‑Detector",
        category: "stego",
        description: "أداة لكشف البيانات المخفية في الصور والصوت والفيديو",
        githubUrl: "https://github.com/CYBEREYE-001/STEG-Detector",
        os: ["windows", "linux", "macos"],
        size: "3.4 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-16",
        downloads: 11000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "STEG‑Detector هي أداة لكشف البيانات المخفية في الصور، الصوت، والفيديو باستخدام تحليل إحصائي. تستخدم في كشف steganography عبر عدة صيغ ملفات."
    },
    {
        id: "stego-toolkit",
        name: "stego-toolkit",
        category: "stego",
        description: "تجميعة شاملة لأدوات إخفاء واكتشاف البيانات",
        githubUrl: "https://github.com/DominicBreuker/stego-toolkit",
        os: ["linux", "macos"],
        size: "4.2 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-14",
        downloads: 18000,
        rating: 4.5,
        license: "MIT",
        extendedDescription: "stego-toolkit هي تجميعة شاملة لأدوات إخفاء واكتشاف البيانات مثل stegpy، Steghide، f5، وغيرها. تستخدم في مساعدة استرداد أو تحليل محتوى مخفي داخل الصور."
    },
    {
        id: "stegano-thing",
        name: "Stegano-Thing",
        category: "stego",
        description: "أدوات فحص steganography وmetadata متعددة",
        githubUrl: "https://github.com/ret42/Stegano-Thing",
        os: ["linux", "macos"],
        size: "2.8 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-12",
        downloads: 12500,
        rating: 4.3,
        license: "MIT",
        extendedDescription: "Stegano-Thing هي أدوات فحص steganography وmetadata مثل Binwalk، ZXing، Exiftool، وغيرها. تستخدم في تحليل الملفات لاستخراج بيانات خفية باستخدام تقنيات متنوعة."
    },
    {
        id: "redteam-tools",
        name: "RedTeam-Tools",
        category: "exploitation",
        description: "مستودع ضخم يحتوي على أكثر من 150 أداة Red Team",
        githubUrl: "https://github.com/A-poc/RedTeam-Tools",
        os: ["linux", "macos"],
        size: "25.6 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-10",
        downloads: 35000,
        rating: 4.7,
        license: "MIT",
        extendedDescription: "RedTeam-Tools هو مستودع ضخم يحتوي على أكثر من 150 أداة Red Team منظمة حسب الاستخدام. يستخدم في إجراء هجمات متقدمة، اختبارات اختراق حقيقية، وسيناريوهات معقدة."
    },
    {
        id: "ctf-tools",
        name: "CTF_tools",
        category: "reverse",
        description: "مستودع أدوات CTF مصنفة حسب نوع التحدي",
        githubUrl: "https://github.com/gregalletti/CTF_tools",
        os: ["linux", "macos"],
        size: "18.4 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-08",
        downloads: 28000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "CTF_tools هو مستودع أدوات CTF مصنفة حسب نوع التحدي: Web، Crypto، Reverse، إلخ. يستخدم في تسهيل حل تحديات المسابقات باحترافية عالية."
    },
    {
        id: "awesome-recon-tools",
        name: "awesome-recon-tools",
        category: "recon",
        description: "أدوات جمع معلومات منظمة حسب النوع",
        githubUrl: "https://github.com/nateahess/awesome-recon-tools",
        os: ["linux", "macos"],
        size: "5.2 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-06",
        downloads: 22000,
        rating: 4.5,
        license: "MIT",
        extendedDescription: "awesome-recon-tools هي أدوات جمع معلومات (Recon) منظمة حسب النوع: بريد إلكتروني، روابط، شبكات، إلخ. تستخدم في تكوين صورة كاملة عن الهدف قبل الهجوم."
    },
    {
        id: "steg-tools",
        name: "steg-tools",
        category: "stego",
        description: "أدوات تحليل metadata وsteghide متعددة",
        githubUrl: "https://github.com/lucacav/steg-tools",
        os: ["linux", "macos"],
        size: "3.6 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-04",
        downloads: 16000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "steg-tools هي أدوات تحليل metadata وsteghide: binwalk، zsteg، exiftool... تستخدم في التحليل الرقمي الدقيق للكشف عن الإخفاء أو التسريب داخل الصور والملفات."
    },
    {
        id: "frida",
        name: "Frida",
        category: "reverse",
        description: "أداة ديناميكية تسمح بحقن جافاسكربت في العمليات الجارية",
        githubUrl: "https://github.com/frida/frida",
        os: ["windows", "linux", "macos", "android", "ios"],
        size: "8.5 MB",
        version: "16.1.0",
        lastUpdate: "2024-02-01",
        downloads: 75000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "Frida هي أداة ديناميكية تسمح بحقن جافاسكربت في العمليات الجارية (Android, iOS, Windows, Linux). تستخدم في تحليل سلوك التطبيق في التنفيذ الحي والتلاعب الوظيفي."
    },
    {
        id: "dnspy",
        name: "dnSpy",
        category: "reverse",
        description: "محرر ومفكك IL لتطبيقات .NET مع دعم التصحيح والتحرير",
        githubUrl: "https://github.com/dnSpyEx/dnSpy",
        os: ["windows"],
        size: "12.8 MB",
        version: "6.3.0",
        lastUpdate: "2024-01-29",
        downloads: 45000,
        rating: 4.7,
        license: "GPL-3.0",
        extendedDescription: "dnSpy هو محرر ومفكك IL لتطبيقات .NET، يدعم التصحيح والتحرير في الوقت الحقيقي. يستخدم في هندسة عكسية لتطبيقات .NET وتجاوز obfuscation."
    },
    {
        id: "pe-bear",
        name: "PE-bear",
        category: "reverse",
        description: "أداة تحليل ملفات PE مع تحليل AI للـ entropy ونقاط الضعف",
        githubUrl: "https://github.com/hasherezade/pe-bear",
        os: ["windows", "linux", "macos"],
        size: "6.2 MB",
        version: "0.6.0",
        lastUpdate: "2024-01-27",
        downloads: 28000,
        rating: 4.6,
        license: "GPL-3.0",
        extendedDescription: "PE-bear هي أداة تحليل ملفات PE مع تحليل AI للـ entropy ونقاط الضعف، دمج بيانات VirusTotal. تستخدم في فحص سريع وتحليل ملفات Windows التنفيذية."
    },
    {
        id: "imhex",
        name: "ImHex",
        category: "reverse",
        description: "محرر Hex عرضي مفتوح المصدر متعدد المنصات مع دعم scripting",
        githubUrl: "https://github.com/WerWolv/ImHex",
        os: ["windows", "linux", "macos"],
        size: "18.5 MB",
        version: "1.32.0",
        lastUpdate: "2024-01-25",
        downloads: 35000,
        rating: 4.8,
        license: "GPL-2.0",
        extendedDescription: "ImHex هو محرر Hex عرضي مفتوح المصدر متعدد المنصات، يدعم scripting، تحليل YARA، diffing وغيرها. يستخدم في التحرير والاستكشاف اليدوي للثنائيات دون تشفير."
    },
    {
        id: "steghide",
        name: "Steghide",
        category: "stego",
        description: "CLI متقدم لإخفاء ملفات داخل JPEG/BMP/WAV مع دعم تشفير AES",
        githubUrl: "https://github.com/StefanoDeVuono/steghide",
        os: ["windows", "linux", "macos"],
        size: "1.8 MB",
        version: "0.5.1",
        lastUpdate: "2024-01-23",
        downloads: 42000,
        rating: 4.5,
        license: "GPL-2.0",
        extendedDescription: "Steghide هو CLI متقدم لإخفاء ملفات داخل JPEG/BMP/WAV مع دعم تشفير AES وضغط. يستخدم في تخفي بيانات داخل وسائط بصيغ معيارية مع مقاومة الكشف."
    },
    {
        id: "binwalk",
        name: "Binwalk",
        category: "reverse",
        description: "أداة لاكتشاف واستخراج الملفات أو البيانات المدمجة داخل الصور",
        githubUrl: "https://github.com/ReFirmLabs/binwalk",
        os: ["windows", "linux", "macos"],
        size: "3.4 MB",
        version: "2.3.3",
        lastUpdate: "2024-01-21",
        downloads: 55000,
        rating: 4.7,
        license: "MIT",
        extendedDescription: "Binwalk هي أداة لاكتشاف واستخراج الملفات أو البيانات المدمجة داخل الصور أو firmware. تستخدم في تحليل داخلي للملفات المعبأة واستعادة البيانات المخفية."
    },
    {
        id: "zsteg",
        name: "zsteg",
        category: "stego",
        description: "يكشف البيانات المخفية في ملفات PNG, BMP باستخدام تحليل LSB",
        githubUrl: "https://github.com/zed-0xff/zsteg",
        os: ["linux", "macos"],
        size: "0.6 MB",
        version: "0.2.8",
        lastUpdate: "2024-01-19",
        downloads: 25000,
        rating: 4.4,
        license: "MIT",
        extendedDescription: "zsteg يكشف البيانات المخفية في ملفات PNG, BMP باستخدام تحليل LSB & color channels. يستخدم في كشف أنماط Steganography في الصور."
    },
    {
        id: "openstego",
        name: "OpenStego",
        category: "stego",
        description: "أداة Java مجانية لإخفاء البيانات داخل الصور مع دعم watermarking",
        githubUrl: "https://github.com/syvaidya/openstego",
        os: ["windows", "linux", "macos"],
        size: "4.8 MB",
        version: "0.8.0",
        lastUpdate: "2024-01-17",
        downloads: 18000,
        rating: 4.3,
        license: "GPL-2.0",
        extendedDescription: "OpenStego هي أداة Java مجانية لإخفاء البيانات داخل الصور، ودعم watermarking، GUI. تستخدم في مخابأة البيانات وطباعتها invisible، مع حماية حقوق النسخة."
    },
    {
        id: "stegify",
        name: "stegify",
        category: "stego",
        description: "أداة Go CLI تُخفي الملفات في أي صورة باستخدام LSB",
        githubUrl: "https://github.com/makiuchi-d/stegify",
        os: ["windows", "linux", "macos"],
        size: "2.1 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-15",
        downloads: 22000,
        rating: 4.5,
        license: "MIT",
        extendedDescription: "stegify هي أداة Go CLI تُخفي الملفات في أي صورة باستخدام LSB. تستخدم في إخفاء ملفات كاملة داخل وسائط الصور بشفافية تامة."
    },
    {
        id: "stegano-python",
        name: "Stegano (Python)",
        category: "stego",
        description: "مكتبة Steganography تخفي البيانات داخل PNG باستخدام LSB",
        githubUrl: "https://github.com/cedricbonhomme/Stegano",
        os: ["windows", "linux", "macos"],
        size: "0.8 MB",
        version: "1.4.0",
        lastUpdate: "2024-01-13",
        downloads: 15000,
        rating: 4.4,
        license: "GPL-3.0",
        extendedDescription: "Stegano هي مكتبة Steganography تخفي البيانات داخل PNG باستخدام LSB. تستخدم في تطوير برمجي لخدمات stego داخل تطبيقات Python."
    },
    {
        id: "pentestgpt",
        name: "PentestGPT",
        category: "exploitation",
        description: "أداة تعتمد على LLM لتنفيذ pentest أوتوماتيكي بثبات عالي",
        githubUrl: "https://github.com/pen-testing-ai/pentestgpt",
        os: ["windows", "linux", "macos"],
        size: "12.5 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-11",
        downloads: 32000,
        rating: 4.6,
        license: "MIT",
        extendedDescription: "PentestGPT هي أداة تعتمد على LLM (مثل GPT) لتنفيذ pentest أوتوماتيكي بثبات عالي. تستخدم في توليد payloads، تحليل تلقائي، وتقارير جاهزة للنخبة."
    },
    {
        id: "ptf",
        name: "PTF (Penetration Testers Framework)",
        category: "exploitation",
        description: "إطار عمل لتثبيت بيئة أدوات Pentest محترفة حسب PTES",
        githubUrl: "https://github.com/trustedsec/ptf",
        os: ["linux"],
        size: "5.2 MB",
        version: "1.0.0",
        lastUpdate: "2024-01-09",
        downloads: 28000,
        rating: 4.5,
        license: "GPL-3.0",
        extendedDescription: "PTF هو Penetration Testers Framework لتثبيت بيئة أدوات Pentest محترفة حسب PTES. يستخدم في إدارة مركزية لتثبيت الأدوات وتنظيم استخدام الفريق."
    },
    {
        id: "immunity-debugger",
        name: "Immunity Debugger",
        category: "reverse",
        description: "Debugger لنظام Windows يدعم Python scripting لتحليل الثغرات",
        githubUrl: "https://www.immunityinc.com/products/debugger/",
        os: ["windows"],
        size: "35.8 MB",
        version: "1.85",
        lastUpdate: "2024-01-07",
        downloads: 18000,
        rating: 4.7,
        license: "Proprietary",
        extendedDescription: "Immunity Debugger هو Debugger لنظام Windows يدعم Python scripting لتحليل الثغرات واستغلالها. يستخدم في تطوير Exploits وتحليل عميق للبرامج."
    },
    {
        id: "api-monitor",
        name: "API Monitor",
        category: "reverse",
        description: "أداة مراقبة واسترجاع استدعاءات API في التطبيقات أثناء التنفيذ",
        githubUrl: "https://www.rohitab.com/apimonitor",
        os: ["windows"],
        size: "8.4 MB",
        version: "2.0.0",
        lastUpdate: "2024-01-05",
        downloads: 25000,
        rating: 4.4,
        license: "Freeware",
        extendedDescription: "API Monitor هي أداة مراقبة واسترجاع استدعاءات API في التطبيقات أثناء التنفيذ. تستخدم في تتبع تنفيذ البرامج وتحليل سلوكها."
    },
    {
        id: "process-hacker",
        name: "Process Hacker",
        category: "reverse",
        description: "أداة مراقبة عمليات النظام في Windows مع قدرات كشف وتحليل متقدمة",
        githubUrl: "https://processhacker.sourceforge.io/",
        os: ["windows"],
        size: "12.6 MB",
        version: "2.39",
        lastUpdate: "2024-01-03",
        downloads: 45000,
        rating: 4.6,
        license: "GPL-3.0",
        extendedDescription: "Process Hacker هي أداة مراقبة عمليات النظام في Windows مع قدرات كشف وتحليل متقدمة. تستخدم في فحص العمليات، الشبكات، وسلوك البرامج."
    },
    {
        id: "peid",
        name: "PEiD",
        category: "reverse",
        description: "أداة كشف Packers وcryptors المستخدمة في ملفات PE",
        githubUrl: "http://peid.has.it/",
        os: ["windows"],
        size: "2.1 MB",
        version: "0.95",
        lastUpdate: "2024-01-01",
        downloads: 32000,
        rating: 4.3,
        license: "GPL-2.0",
        extendedDescription: "PEiD هي أداة كشف Packers وcryptors المستخدمة في ملفات PE. تستخدم في تحليل الحماية وطرق التغليف."
    },
    {
        id: "scylla",
        name: "Scylla",
        category: "reverse",
        description: "أداة لاستعادة جداول استيراد DLL من ملفات packed",
        githubUrl: "https://github.com/NtQuery/Scylla",
        os: ["windows"],
        size: "1.8 MB",
        version: "0.9.8",
        lastUpdate: "2023-12-30",
        downloads: 28000,
        rating: 4.5,
        license: "GPL-3.0",
        extendedDescription: "Scylla هي أداة لاستعادة جداول استيراد DLL من ملفات packed. تستخدم في استعادة بيانات الاستيراد للملفات المحمية."
    },
    {
        id: "cff-explorer",
        name: "CFF Explorer",
        category: "reverse",
        description: "أداة لتحليل ملفات PE، تحتوي على محرر هيكلي شامل",
        githubUrl: "https://ntcore.com/?page_id=388",
        os: ["windows"],
        size: "4.2 MB",
        version: "8.0.0",
        lastUpdate: "2023-12-28",
        downloads: 35000,
        rating: 4.4,
        license: "Freeware",
        extendedDescription: "CFF Explorer هي أداة لتحليل ملفات PE، تحتوي على محرر هيكلي شامل. تستخدم في تحليل شامل لهيكلية ملفات Windows التنفيذية."
    },
    {
        id: "hopper",
        name: "Hopper",
        category: "reverse",
        description: "Decompiler لأنظمة macOS وLinux، يسمح بتحليل التعليمات البرمجية الأصلية",
        githubUrl: "https://www.hopperapp.com/",
        os: ["macos", "linux"],
        size: "45.2 MB",
        version: "5.11.0",
        lastUpdate: "2023-12-26",
        downloads: 22000,
        rating: 4.8,
        license: "Proprietary",
        extendedDescription: "Hopper هو Decompiler لأنظمة macOS وLinux، يسمح بتحليل التعليمات البرمجية الأصلية. يستخدم في هندسة عكسية وتحليل تطبيقات أصلية."
    },
    {
        id: "jadx",
        name: "JaDx",
        category: "reverse",
        description: "Decompiler لتحويل ملفات APK إلى شفرة Java قابلة للتحليل",
        githubUrl: "https://github.com/skylot/jadx",
        os: ["windows", "linux", "macos"],
        size: "15.8 MB",
        version: "1.4.7",
        lastUpdate: "2023-12-24",
        downloads: 68000,
        rating: 4.7,
        license: "Apache-2.0",
        extendedDescription: "JaDx هو Decompiler لتحويل ملفات APK إلى شفرة Java قابلة للتحليل. يستخدم في تحليل تطبيقات Android بسهولة."
    },
    {
        id: "snowdrop",
        name: "Snowdrop",
        category: "stego",
        description: "أداة Watermarking ونصوص steganography لإخفاء الرسائل داخل نصوص غير مرئية",
        githubUrl: "https://github.com/buckket/snowdrop",
        os: ["windows", "linux", "macos"],
        size: "0.4 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-22",
        downloads: 8500,
        rating: 4.2,
        license: "MIT",
        extendedDescription: "Snowdrop هي أداة Watermarking ونصوص steganography لإخفاء الرسائل داخل نصوص غير مرئية. تستخدم في تخفي الرسائل النصية بسرية."
    },
    {
        id: "stegoshare",
        name: "Stegoshare",
        category: "stego",
        description: "أداة Java لإخفاء بيانات في ملفات WAV مع دعم متعددة",
        githubUrl: "https://github.com/Stegoshare/stegoshare",
        os: ["windows", "linux", "macos"],
        size: "3.2 MB",
        version: "1.0.0",
        lastUpdate: "2023-12-20",
        downloads: 12000,
        rating: 4.3,
        license: "GPL-3.0",
        extendedDescription: "Stegoshare هي أداة Java لإخفاء بيانات في ملفات WAV مع دعم متعددة. تستخدم في استخدام في تحديات stego متعددة الوسائط."
    },
    {
        id: "outguess",
        name: "OutGuess",
        category: "stego",
        description: "أداة Steganography عامة تدعم ملفات JPEG وBMP وAU",
        githubUrl: "https://github.com/jbremer/outguess",
        os: ["linux", "macos"],
        size: "1.2 MB",
        version: "0.2",
        lastUpdate: "2023-12-18",
        downloads: 18000,
        rating: 4.4,
        license: "GPL-2.0",
        extendedDescription: "OutGuess هي أداة Steganography عامة تدعم ملفات JPEG وBMP وAU. تستخدم في إخفاء واسترجاع البيانات ضمن الصور."
    },
    {
        id: "immuniweb",
        name: "ImmuniWeb",
        category: "recon",
        description: "منصة تقييم أمن التطبيقات السحابية باستخدام الذكاء الاصطناعي",
        githubUrl: "https://www.immuniweb.com/",
        os: ["web"],
        size: "0 MB",
        version: "1.0.0",
        lastUpdate: "2024-02-05",
        downloads: 15000,
        rating: 4.6,
        license: "Proprietary",
        extendedDescription: "ImmuniWeb هي منصة تقييم أمن التطبيقات السحابية باستخدام الذكاء الاصطناعي. تستخدم في تحليل شامل ونقاط ضعف أمان التطبيقات."
    },
    {
        id: "spiderfoot",
        name: "SpiderFoot",
        category: "osint",
        description: "أداة OSINT شاملة لجمع وتحليل البيانات من مصادر متعددة",
        githubUrl: "https://github.com/smicallef/spiderfoot",
        os: ["windows", "linux", "macos"],
        size: "8.5 MB",
        version: "4.0.0",
        lastUpdate: "2024-02-03",
        downloads: 28000,
        rating: 4.7,
        license: "GPL-2.0",
        extendedDescription: "SpiderFoot هي أداة OSINT شاملة لجمع وتحليل البيانات من مصادر متعددة. تستخدم في جمع معلومات كاملة حول الهدف."
    },
    {
        id: "osint-framework",
        name: "OSINT Framework",
        category: "osint",
        description: "تجميع روابط وأدوات OSINT منظمة حسب النوع والاستخدام",
        githubUrl: "https://osintframework.com/",
        os: ["web"],
        size: "0 MB",
        version: "1.0.0",
        lastUpdate: "2024-02-01",
        downloads: 45000,
        rating: 4.8,
        license: "MIT",
        extendedDescription: "OSINT Framework هو تجميع روابط وأدوات OSINT منظمة حسب النوع والاستخدام. يستخدم كمرجع شامل لأدوات OSINT."
    },
    {
        id: "mimikatz",
        name: "Mimikatz",
        category: "exploitation",
        description: "أداة استخراج كلمات السر من الذاكرة",
        githubUrl: "https://github.com/gentilkiwi/mimikatz",
        os: ["windows"],
        size: "2.8 MB",
        version: "2.2.0",
        lastUpdate: "2024-01-30",
        downloads: 85000,
        rating: 4.9,
        license: "BSD-3-Clause",
        extendedDescription: "Mimikatz هي أداة استخراج كلمات السر من الذاكرة. تستخدم في سرقة بيانات الاعتماد في بيئات Windows."
    },
    {
        id: "crackmapexec",
        name: "CrackMapExec",
        category: "exploitation",
        description: "أداة إدارة اختراق الشبكات",
        githubUrl: "https://github.com/byt3bl33d3r/CrackMapExec",
        os: ["linux", "macos"],
        size: "4.2 MB",
        version: "5.4.0",
        lastUpdate: "2024-01-28",
        downloads: 52000,
        rating: 4.8,
        license: "BSD-3-Clause",
        extendedDescription: "CrackMapExec هي أداة إدارة اختراق الشبكات. تستخدم في تسهيل إدارة العمليات الهجومية على الشبكات."
    },
    {
        id: "veil-framework",
        name: "Veil-Framework",
        category: "exploitation",
        description: "أداة توليد Payloads لتجاوز مضادات الفيروسات",
        githubUrl: "https://github.com/Veil-Framework/Veil",
        os: ["linux"],
        size: "15.6 MB",
        version: "3.0.0",
        lastUpdate: "2024-01-26",
        downloads: 38000,
        rating: 4.6,
        license: "GPL-3.0",
        extendedDescription: "Veil-Framework هي أداة توليد Payloads لتجاوز مضادات الفيروسات. تستخدم في إنشاء شفرات تخفي استغلالات."
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = toolsData;
} 